-- ============================================================
--  Run these in MySQL Workbench BEFORE starting the application
-- ============================================================

-- Step 1: Create the schema
CREATE SCHEMA IF NOT EXISTS ormlearn;
USE ormlearn;

-- Step 2: Create the country table
-- co_code = 2-char ISO country code (primary key)
-- co_name = full country name
CREATE TABLE IF NOT EXISTS country (
    co_code VARCHAR(2) PRIMARY KEY,
    co_name VARCHAR(50)
);

-- Step 3: Insert all countries
-- (truncate first if re-running to avoid duplicate key errors)
TRUNCATE TABLE country;

insert into country (co_code, co_name) values ('IN', 'India');
insert into country (co_code, co_name) values ('US', 'United States');
insert into country (co_code, co_name) values ('AF', 'Afghanistan');
insert into country (co_code, co_name) values ('AL', 'Albania');
insert into country (co_code, co_name) values ('DZ', 'Algeria');
insert into country (co_code, co_name) values ('AS', 'American Samoa');
insert into country (co_code, co_name) values ('AD', 'Andorra');
insert into country (co_code, co_name) values ('AO', 'Angola');
insert into country (co_code, co_name) values ('AI', 'Anguilla');
insert into country (co_code, co_name) values ('AQ', 'Antarctica');
insert into country (co_code, co_name) values ('AG', 'Antigua and Barbuda');
insert into country (co_code, co_name) values ('AR', 'Argentina');
insert into country (co_code, co_name) values ('AM', 'Armenia');
insert into country (co_code, co_name) values ('AW', 'Aruba');
insert into country (co_code, co_name) values ('AU', 'Australia');
insert into country (co_code, co_name) values ('AT', 'Austria');
insert into country (co_code, co_name) values ('AZ', 'Azerbaijan');
insert into country (co_code, co_name) values ('BS', 'Bahamas');
insert into country (co_code, co_name) values ('BH', 'Bahrain');
insert into country (co_code, co_name) values ('BD', 'Bangladesh');
insert into country (co_code, co_name) values ('BB', 'Barbados');
insert into country (co_code, co_name) values ('BY', 'Belarus');
insert into country (co_code, co_name) values ('BE', 'Belgium');
insert into country (co_code, co_name) values ('BZ', 'Belize');
insert into country (co_code, co_name) values ('BJ', 'Benin');
insert into country (co_code, co_name) values ('BM', 'Bermuda');
insert into country (co_code, co_name) values ('BT', 'Bhutan');
insert into country (co_code, co_name) values ('BO', 'Bolivia, Plurinational State of');
insert into country (co_code, co_name) values ('BA', 'Bosnia and Herzegovina');
insert into country (co_code, co_name) values ('BW', 'Botswana');
insert into country (co_code, co_name) values ('BR', 'Brazil');
insert into country (co_code, co_name) values ('BN', 'Brunei Darussalam');
insert into country (co_code, co_name) values ('BG', 'Bulgaria');
insert into country (co_code, co_name) values ('BF', 'Burkina Faso');
insert into country (co_code, co_name) values ('BI', 'Burundi');
insert into country (co_code, co_name) values ('KH', 'Cambodia');
insert into country (co_code, co_name) values ('CM', 'Cameroon');
insert into country (co_code, co_name) values ('CA', 'Canada');
insert into country (co_code, co_name) values ('CF', 'Central African Republic');
insert into country (co_code, co_name) values ('TD', 'Chad');
insert into country (co_code, co_name) values ('CL', 'Chile');
insert into country (co_code, co_name) values ('CN', 'China');
insert into country (co_code, co_name) values ('CO', 'Colombia');
insert into country (co_code, co_name) values ('CG', 'Congo');
insert into country (co_code, co_name) values ('CR', 'Costa Rica');
insert into country (co_code, co_name) values ('HR', 'Croatia');
insert into country (co_code, co_name) values ('CU', 'Cuba');
insert into country (co_code, co_name) values ('CY', 'Cyprus');
insert into country (co_code, co_name) values ('CZ', 'Czech Republic');
insert into country (co_code, co_name) values ('DK', 'Denmark');
insert into country (co_code, co_name) values ('DJ', 'Djibouti');
insert into country (co_code, co_name) values ('DM', 'Dominica');
insert into country (co_code, co_name) values ('DO', 'Dominican Republic');
insert into country (co_code, co_name) values ('EC', 'Ecuador');
insert into country (co_code, co_name) values ('EG', 'Egypt');
insert into country (co_code, co_name) values ('SV', 'El Salvador');
insert into country (co_code, co_name) values ('GQ', 'Equatorial Guinea');
insert into country (co_code, co_name) values ('ER', 'Eritrea');
insert into country (co_code, co_name) values ('EE', 'Estonia');
insert into country (co_code, co_name) values ('ET', 'Ethiopia');
insert into country (co_code, co_name) values ('FJ', 'Fiji');
insert into country (co_code, co_name) values ('FI', 'Finland');
insert into country (co_code, co_name) values ('FR', 'France');
insert into country (co_code, co_name) values ('GA', 'Gabon');
insert into country (co_code, co_name) values ('GM', 'Gambia');
insert into country (co_code, co_name) values ('GE', 'Georgia');
insert into country (co_code, co_name) values ('DE', 'Germany');
insert into country (co_code, co_name) values ('GH', 'Ghana');
insert into country (co_code, co_name) values ('GR', 'Greece');
insert into country (co_code, co_name) values ('GT', 'Guatemala');
insert into country (co_code, co_name) values ('GN', 'Guinea');
insert into country (co_code, co_name) values ('GY', 'Guyana');
insert into country (co_code, co_name) values ('HT', 'Haiti');
insert into country (co_code, co_name) values ('HN', 'Honduras');
insert into country (co_code, co_name) values ('HK', 'Hong Kong');
insert into country (co_code, co_name) values ('HU', 'Hungary');
insert into country (co_code, co_name) values ('IS', 'Iceland');
insert into country (co_code, co_name) values ('ID', 'Indonesia');
insert into country (co_code, co_name) values ('IR', 'Iran, Islamic Republic of');
insert into country (co_code, co_name) values ('IQ', 'Iraq');
insert into country (co_code, co_name) values ('IE', 'Ireland');
insert into country (co_code, co_name) values ('IL', 'Israel');
insert into country (co_code, co_name) values ('IT', 'Italy');
insert into country (co_code, co_name) values ('JM', 'Jamaica');
insert into country (co_code, co_name) values ('JP', 'Japan');
insert into country (co_code, co_name) values ('JO', 'Jordan');
insert into country (co_code, co_name) values ('KZ', 'Kazakhstan');
insert into country (co_code, co_name) values ('KE', 'Kenya');
insert into country (co_code, co_name) values ('KW', 'Kuwait');
insert into country (co_code, co_name) values ('KG', 'Kyrgyzstan');
insert into country (co_code, co_name) values ('LV', 'Latvia');
insert into country (co_code, co_name) values ('LB', 'Lebanon');
insert into country (co_code, co_name) values ('LR', 'Liberia');
insert into country (co_code, co_name) values ('LY', 'Libya');
insert into country (co_code, co_name) values ('LT', 'Lithuania');
insert into country (co_code, co_name) values ('LU', 'Luxembourg');
insert into country (co_code, co_name) values ('MG', 'Madagascar');
insert into country (co_code, co_name) values ('MW', 'Malawi');
insert into country (co_code, co_name) values ('MY', 'Malaysia');
insert into country (co_code, co_name) values ('MV', 'Maldives');
insert into country (co_code, co_name) values ('ML', 'Mali');
insert into country (co_code, co_name) values ('MT', 'Malta');
insert into country (co_code, co_name) values ('MQ', 'Martinique');
insert into country (co_code, co_name) values ('MR', 'Mauritania');
insert into country (co_code, co_name) values ('MU', 'Mauritius');
insert into country (co_code, co_name) values ('MX', 'Mexico');
insert into country (co_code, co_name) values ('MD', 'Moldova, Republic of');
insert into country (co_code, co_name) values ('MC', 'Monaco');
insert into country (co_code, co_name) values ('MN', 'Mongolia');
insert into country (co_code, co_name) values ('ME', 'Montenegro');
insert into country (co_code, co_name) values ('MA', 'Morocco');
insert into country (co_code, co_name) values ('MZ', 'Mozambique');
insert into country (co_code, co_name) values ('MM', 'Myanmar');
insert into country (co_code, co_name) values ('NA', 'Namibia');
insert into country (co_code, co_name) values ('NP', 'Nepal');
insert into country (co_code, co_name) values ('NL', 'Netherlands');
insert into country (co_code, co_name) values ('NZ', 'New Zealand');
insert into country (co_code, co_name) values ('NI', 'Nicaragua');
insert into country (co_code, co_name) values ('NE', 'Niger');
insert into country (co_code, co_name) values ('NG', 'Nigeria');
insert into country (co_code, co_name) values ('NO', 'Norway');
insert into country (co_code, co_name) values ('OM', 'Oman');
insert into country (co_code, co_name) values ('PK', 'Pakistan');
insert into country (co_code, co_name) values ('PA', 'Panama');
insert into country (co_code, co_name) values ('PG', 'Papua New Guinea');
insert into country (co_code, co_name) values ('PY', 'Paraguay');
insert into country (co_code, co_name) values ('PE', 'Peru');
insert into country (co_code, co_name) values ('PH', 'Philippines');
insert into country (co_code, co_name) values ('PL', 'Poland');
insert into country (co_code, co_name) values ('PT', 'Portugal');
insert into country (co_code, co_name) values ('QA', 'Qatar');
insert into country (co_code, co_name) values ('RO', 'Romania');
insert into country (co_code, co_name) values ('RU', 'Russian Federation');
insert into country (co_code, co_name) values ('RW', 'Rwanda');
insert into country (co_code, co_name) values ('SA', 'Saudi Arabia');
insert into country (co_code, co_name) values ('SN', 'Senegal');
insert into country (co_code, co_name) values ('RS', 'Serbia');
insert into country (co_code, co_name) values ('SC', 'Seychelles');
insert into country (co_code, co_name) values ('SL', 'Sierra Leone');
insert into country (co_code, co_name) values ('SG', 'Singapore');
insert into country (co_code, co_name) values ('SK', 'Slovakia');
insert into country (co_code, co_name) values ('SI', 'Slovenia');
insert into country (co_code, co_name) values ('SO', 'Somalia');
insert into country (co_code, co_name) values ('ZA', 'South Africa');
insert into country (co_code, co_name) values ('SS', 'South Sudan');
insert into country (co_code, co_name) values ('ES', 'Spain');
insert into country (co_code, co_name) values ('LK', 'Sri Lanka');
insert into country (co_code, co_name) values ('SD', 'Sudan');
insert into country (co_code, co_name) values ('SR', 'Suriname');
insert into country (co_code, co_name) values ('SE', 'Sweden');
insert into country (co_code, co_name) values ('CH', 'Switzerland');
insert into country (co_code, co_name) values ('SY', 'Syrian Arab Republic');
insert into country (co_code, co_name) values ('TW', 'Taiwan, Province of China');
insert into country (co_code, co_name) values ('TJ', 'Tajikistan');
insert into country (co_code, co_name) values ('TZ', 'Tanzania, United Republic of');
insert into country (co_code, co_name) values ('TH', 'Thailand');
insert into country (co_code, co_name) values ('TG', 'Togo');
insert into country (co_code, co_name) values ('TO', 'Tonga');
insert into country (co_code, co_name) values ('TT', 'Trinidad and Tobago');
insert into country (co_code, co_name) values ('TN', 'Tunisia');
insert into country (co_code, co_name) values ('TR', 'Turkey');
insert into country (co_code, co_name) values ('TM', 'Turkmenistan');
insert into country (co_code, co_name) values ('TV', 'Tuvalu');
insert into country (co_code, co_name) values ('UG', 'Uganda');
insert into country (co_code, co_name) values ('UA', 'Ukraine');
insert into country (co_code, co_name) values ('AE', 'United Arab Emirates');
insert into country (co_code, co_name) values ('GB', 'United Kingdom');
insert into country (co_code, co_name) values ('UY', 'Uruguay');
insert into country (co_code, co_name) values ('UZ', 'Uzbekistan');
insert into country (co_code, co_name) values ('VU', 'Vanuatu');
insert into country (co_code, co_name) values ('VE', 'Venezuela, Bolivarian Republic of');
insert into country (co_code, co_name) values ('VN', 'Viet Nam');
insert into country (co_code, co_name) values ('YE', 'Yemen');
insert into country (co_code, co_name) values ('ZM', 'Zambia');
insert into country (co_code, co_name) values ('ZW', 'Zimbabwe');
