# Run the server on port 8083 as specified in the exercise
server.port=8083

# Application logs
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Log pattern
logging.pattern.console=%d{dd-MM-yy HH:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n
